#! /bin/sh

#localdir="$(dirname $1)"

pdftotext $1 $1.1.tmp

sed 's/^\ *//g' $1.1.tmp > $1.2.tmp

sed -e :a -e '$!N;s/\n\(^[a-z]\)/\ \1/;ta' -e 'P;D' $1.2.tmp > $1.3.tmp

sed 's/^\ /\n/g' $1.3.tmp > $1.4.tmp

sed 's/\.$/\.\n/g' $1.4.tmp > $1.5.tmp

sed -r '/[[:lower:]]/!{a
i
}' $1.5.tmp > $1.6.tmp

uniq $1.6.tmp > $1.7.tmp

mv $1.7.tmp $1.txt

rm *.tmp

gvim --remote-tab-silent $1.txt
